<?php

namespace ABS\BlogBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByDate()
    {
		return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM ABSBlogBundle:Article a ORDER BY a.date DESC'
            )
            ->getResult();
    }
}
