<?php

namespace ABS\BlogBundle\Entity;

/**
 * CelebrityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CelebrityRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByName()
    {
		return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM ABSBlogBundle:Celebrity c ORDER BY c.name ASC'
            )
            ->getResult();
    }
}
